### ISSUE TITLE
Maskinporten-client - bruk av proxy

### ISSUE THREAD

**Issue by dagleger** [difi/dokumentasjonsprosjektet#112]
Maskinporten-client ser ut til å mangle støtte for konfigurering av proxy.
I noen driftsmiljøer er dette en nødvendighet, så det hadde vært fint å få lagt inn.

**Comment by thorsortevik** [comment]
Hei,

Er det jwt-generatoren du mener her?

mvh
Thor Kristian
Digdir

**Comment by dagleger** [comment]
Nei, jeg mener HttpClientBuilder i Maskinportenklient.acquireAccessToken(). Det burde f.ex. finnes properties for proxyhost/-port som, hvis satt, fører til at HttpClientBuilder.setProxy() kalles.

**Comment by aamundbr** [comment]
Hei igjen!

Litt usikker på hvilket kodeprosjekt du refererer til nå. Vi har https://github.com/difi/jwt-grant-generator, men formålet med det prosjektet er mest å vise eksempler på hvordan du bygger et riktig jwt-grant , og er ikke ment / komplett nok som produksjonskode. Dette prosjektet har heller ingen Maskinportenklient.acquireAccessToken() - metode.
