### ISSUE TITLE
ELMA sin swagger-spesifikasjon som nedlastbar fil

### ISSUE THREAD

**Issue by omega** [difi/dokumentasjonsprosjektet#113]
Det hadde vært veldig kjekt for automatisering om selve swagger-spesifikasjonen for ELMA lå som en egen fil, og ikke som en string i html'en.

**Comment by omega** [comment]
La også merke til at jeg tror Redoc skriver den om fra Swagger 2.0 til OpenAPI 3.0, det man laster ned er ørlitt annerledes enn det som ligger i HTML'en (dette mer til info om andre blir forvirret slik jeg ble når jeg prøvde å laste ned og sånt)

**Comment by FrodeBjerkholt** [comment]
Swagger dokumentasjonen skal ikke brukes lenger. Riktig dokumentasjon er https://smp.difi.no/rest/resources/docs/index.html
