### ISSUE TITLE
Elma Swagger spec har feil `in` på noen parametere

### ISSUE THREAD

**Issue by omega** [difi/dokumentasjonsprosjektet#114]
```
 "/api/organizations/{scheme}::{value}/processes": {
```

skulle tilsi at `scheme` og `value` skal ha `in: "path"`, men det ser ut til å være `in: "query"` på begge. Da blir klienter forvirret når man genererer de.

**Comment by FrodeBjerkholt** [comment]
Swagger dokumentasjonen skal ikke brukes lenger. Riktig dokumentasjon er https://smp.difi.no/rest/resources/docs/index.html
