### ISSUE TITLE
Dokumentere/spesifisere authentication for swagger/openapi

### ISSUE THREAD

**Issue by omega** [difi/dokumentasjonsprosjektet#115]
Jeg sliter litt med authentication mot API'et som er spesifisert på https://difi.github.io/felleslosninger/elma_swagger.html

Selve swagger-spec'en sier ingen security schemes, så jeg forsøkte med basic auth manuelt via `Authorization: Basic <base64>`, men blir uansett kun redirected til `/login` som virker litt rart for et API? Mangler det noe på basePath?

(jeg går mot `https://smp.difi.no` hvis det har noe å si hvilket miljø)

Er swagger-apiet på noen måte relatert til https://smp.difi.no/rest/resources/docs/index.html?

**Comment by FrodeBjerkholt** [comment]
Swagger dokumentasjonen skal ikke brukes lenger. Riktig dokumentasjon er [https://smp.difi.no/rest/resources/docs/index.html](https://smp.difi.no/rest/resources/docs/index.html)
