### ISSUE TITLE
Integration swagger link is dead

### ISSUE THREAD

**Issue by hadrienk** [difi/dokumentasjonsprosjektet#188]
The link to the swagger documentation of the integration API does not work.
https://integrasjon-ver2.difi.no/swagger-ui/

> OpenAPI-dokumentasjon
REST-grensesnittet er dokumentert her.

```json
{
  "status":401,
  "error":"Unauthorized",
  "error_description":"Full authentication is required to access this resource",
  "correlation_id":"5415dd52-5dcd-438e-be61-b28f79087888",
  "timestamp":"2021-11-04T19:20:52.035Z"
}
```

**Comment by eirikhoem** [comment]
thank you for feedback, we'll publish a fix very soon

**Comment by eirikhoem** [comment]
it's fixed now
