### ISSUE TITLE
Maskinporten: Lenke til skjema for tildeling av prefix er død 

### ISSUE THREAD

**Issue by johnksv** [difi/dokumentasjonsprosjektet#231]
Lenke til skjema som benyttes for manuell tildeling av prefix er død (https://forms.office.com/Pages/ResponsePage.aspx?id=D1aOAK8I7EygVrNUR1A5ka_Oknk2ND5DhEKnqlTuZMlUMVNWWVYwSlhTWlpRTjQwWEVDS09EUFVWWS4u).

https://github.com/felleslosninger/docs/blob/gh-pages/_docs/Maskinporten/maskinporten_guide_apitilbyder.md#1-manuell-tildeling-av-prefix

**Comment by thorsortevik** [comment]
Hei, takk for innspillet. Jeg har endret til korrekt lenke nå :)
