### ISSUE TITLE
eFormidling Ipunkt - Oppdater info om anbefalt Java-versjon (11 og JRE)

### ISSUE THREAD

**Issue by o-l-a-v** [difi/dokumentasjonsprosjektet#376]
## Kontekst

Dok ber om Java 8 (JRE? JDK?) **og** "Java Cryptography Extension (JCE)".

* <https://docs.digdir.no/assets/search.html?query=adopt>

Support har bekreftet at man kan bruke Java 11 JRE. Seneste versjon finner man her:

* <https://adoptium.net/temurin/releases/?os=windows&arch=x64&package=jre&version=11>

Av det jeg kan lese trenger man ikke "Java Cryptography Extension (JCE)" lenger.

* <https://www.oracle.com/java/technologies/javase-jce-all-downloads.html>
  > The unlimited policy files are required only for JDK 8, 7, and 6 updates earlier than 8u161, 7u171, and 6u181. On those versions and later, the stronger cryptographic algorithms are available by default.

## Forespørsel

Oppdater dok om anbefalt Java-versjon til å være versjon 11 og JRE, samt fjern info om "Java Cryptography Extension (JCE)".

* Versjon 21 i fremtiden når: <https://github.com/digdir/roadmap/issues/65>

**Comment by steinarhenriksen** [comment]
Hei og takk for innspel 👍 

Det er Java 8 som er anbefalt fordi dette er Java-versjonen som kildekoden testes med. Java 11 er verifisert og fungerer, men testes ikkje jevnlig.

Me kjem derfor ikkje til å gjere endringa du foreslår no.

Det jobbes framover med oppgradering til Java 21+. Når det arbeidet er ferdig oppdateres naturligvis dokumentasjonen.

**Comment by o-l-a-v** [comment]
@steinarhenriksen 

Dere kan likevel fjerne info om JCE, ref:

* <https://www.oracle.com/java/technologies/javase-jce-all-downloads.html>

> The unlimited policy files are required only for JDK 8, 7, and 6 updates earlier than 8u161, 7u171, and 6u181. On those versions and later, the stronger cryptographic algorithms are available by default.

Og dere kan legge til info om at kun JRE trengs, ikke JDK.

**Comment by steinarhenriksen** [comment]
Det burde være slik, men eg er usikker på om det stemmer at berre JRE trengs. Sidan JDK eksplisitt er spesifisert i dokumentasjonen kan det hende at det er klasser frå JDK i bruk.

Det som gjeld JCE er eg einig i.

**Comment by o-l-a-v** [comment]
Support sa til oss at JRE er nok. Vi har kjørt på det siden april i år. JRE 11 altså.
