### ISSUE TITLE
eFormidling Ipunkt - Stopper Ipunkt om man stopper KOSMOS-tjenesten?

### ISSUE THREAD

**Issue by o-l-a-v** [difi/dokumentasjonsprosjektet#377]
## Bakgrunn

Det hadde vært kjekt å vite om å stoppe Windows-tjenesten `kosmossvc` også stopper Ipunkt, f.eks. i forbindelse med oppgradering av Java-installasjon. Tenker da på når man kjører KOSMOS som en Windows-tjeneste, som også orkestrerer Ipunkt, ref:

* <https://docs.digdir.no/docs/eFormidling/installasjon/automatisk_oppgradering#k%C3%B8yra-som-windows-teneste>

Om det er nok å stoppe KOSMOS-tjenesten med f.eks. PowerShell `Stop-Service -Name 'kosmossvc'`, oppdatere Java, så PowerShell `Start-Service -Name 'kosmossvc'`, hadde det gjort prosessen rask og enkel.

Ettersom jeg ikke finner info på dette tenker jeg heller å sette `kosmossvc` service startup type til "Manual", reboot, oppdatere Java, sett `kosmossvc` startup type tilbake til "Automatic", start `kosmossvc`.

* Edit: Gjorde dette i går ^, funka bra.

## Forespørsel

Legg til info i dok eller F.A.Q:

* Konkret: Stopper Ipunkt om man stopper KOSMOS-tjenesten `kosmossvc`?
* Generell info om prosedyre for Java-oppdatering hadde vært nyttig.
  * Relatert: #376

**Comment by steinarhenriksen** [comment]
@johannmo ^ hugsar du korleis det vart gjort?

**Comment by johannmo** [comment]
KOSMOS-tenesta stoppar ikkje integrasjonspunktet, men det hadde heilt klart vore nyttig funksjonalitet.

**Comment by johannmo** [comment]
@o-l-a-v Takk for innspel! Me skal oppdatera dokumentasjonen, og ta det andre forslaget til vurdering i teamet.

**Comment by johannmo** [comment]
@o-l-a-v Takk for innspel! Me skal oppdatera dokumentasjonen, og ta det andre forslaget til vurdering i teamet.
