### ISSUE TITLE
Link til KRR OpenAPI dokumentasjon krever autentisering.

### ISSUE THREAD

**Issue by cerpusoddarne** [difi/dokumentasjonsprosjektet#53]
Jeg prøver å følge linken til OpenAPI dokumentasjonen av KRR APIet her: [https://difi.github.io/felleslosninger/oppslagstjenesten_rest.html#endepunkt](https://difi.github.io/felleslosninger/oppslagstjenesten_rest.html#endepunkt) men blir stoppet med en 401 og responsen:

{"status":401,"error":"Unauthorized","error_description":"Full authentication is required to access this resource","correlation_id":"47ba710c-c656-4616-bf2e-1eb5638d509e","timestamp":"2020-03-05T09:29:51.971Z"} 

Direktelink til siden som krever autentisering: [https://oidc-ver2.difi.no/kontaktinfo-oauth2-server/rest/swagger-ui.html#/Personer](https://oidc-ver2.difi.no/kontaktinfo-oauth2-server/rest/swagger-ui.html#/Personer)

Feil link? Feil oppsett?

**Comment by thorsortevik** [comment]
Ser ut som denne feilen er rettet uten å kvittere ut issue her.
