### ISSUE TITLE
Tilbakemeldingar Utvida møteavlevering

### ISSUE THREAD

**Issue by hoyum** [difi/dokumentasjonsprosjektet#62]
Tilbakemeldingar på https://difi.github.io/felleslosninger/einnsyn_utvida_moeteavlevering.html

**Comment by SteinarAbrahamsen** [comment]
**Bruk av møtesakstype i møtesaksregistrering**
Denne er i orden. Vi forstår det slik:
Møtesaksregistrering kan ha ulike møtesakstyper som "Politisk sak" og "Referatsak".
Møtesaksregistrering har relasjon til en dokumentbeskrivelse som "Vedtak" eller "Saksprotokoll".

**Rekkefølge på saksframlegg**
Rekkefølge for behandling av  saker i et møte (saksliste) er egenskaper ved møtesaksregistreringen. 

Møtemappen inneholder egenskaper for møtet som tid og sted, men skal ikke brukes til å angi  rekkefølge for behandling av møtesakene.

**Status for møtebehandling**
Denne er i orden. Møtesaksdokument kan gis status for "Ferdig behandlet". Dere bør ta høyde for andre verdier som "Godkjent" og "Arkivert".

**Møtedokumentregistreringstyper**
Denne er i orden: Møtedokumentregistreringstyper som "Møteprotokoll" og "Innkalling" bør kunne benyttes. 

**Generelt**
Dere bør ta en gjennomgang av skrivemåter. Dere benytter f.eks møtesaksregistrering og moetsaksregistering om hverandre i json filene..
